aclfile "/Users/sacvenka/Desktop/OCI-Cache/oci-cache-modules/module-ociadmin/tmp/users_in_oci.acl"
loadmodule /Users/sacvenka/Desktop/OCI-Cache/oci-cache-modules/module-ociadmin/target/debug/libociadmin.dylib
enable-module-command yes
enable-debug-command yes
