name: Spellcheck
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@e3cd8e9aec4587ec73bc0e60745aafd45c37aa2e # 0.60.0
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install typos
        uses: taiki-e/install-action@db5fb34fa772531a3ece57ca434f579eb334e0fb # v2.75.30
        with:
          tool: typos
      - name: Run typos
        run: typos --config=.github/typos.toml
