name: 'Build jemalloc (Fedora only)'
description: 'Build jemalloc on Fedora with enable-jemalloc-prefix'
runs:
  using: "composite"
  steps:
    - run: |
        dnf -y install autoconf make gcc awk curl unzip
        curl -L -o jemalloc-5.3.0.zip https://github.com/jemalloc/jemalloc/archive/refs/tags/5.3.0.zip
        unzip jemalloc-5.3.0.zip
        cd jemalloc-5.3.0
        ./autogen.sh
        ./configure --prefix=/opt/jemalloc --enable-jemalloc-prefix
        make -j$(nproc)
        make install
      shell: bash
    - run: |
        echo "LD_LIBRARY_PATH=/opt/jemalloc/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "LDFLAGS=-L/opt/jemalloc/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/opt/jemalloc/include" >> $GITHUB_ENV
      shell: bash
