import abc
import typing


class BaseReqResFileProcessor(abc.ABC):
    def __init__(self, path: str):
        self._path = path

    @property
    def path(self) -> str:
        return self._path

    @abc.abstractmethod
    def process(self) -> None:
        """
        This function processes a single file generated by logreqres.c
        """
        pass

    @abc.abstractmethod
    def _get_results(self) -> typing.Any:
        pass

    @property
    def results(self) -> typing.Any:
        return self._get_results()

    def read_file(self) -> str:
        # Convert file to StringIO in order to minimize IO operations
        with open(self.path, "r", newline="\r\n", encoding="latin-1") as f:
            return f.read()
