port 7000
bind 127.0.0.1
protected-mode no
dir /google/src/cloud/nandihalli/research-active-active-support/google3/valkey_git/src/active_active_tests
dbfilename dump_a.rdb
appendonly no
replica-read-only no
active-replica yes
multi-master yes
rreplay-pending-max-entries 5
repl-timeout 30
repl-backlog-size 16384
logfile /google/src/cloud/nandihalli/research-active-active-support/google3/valkey_git/src/active_active_tests/node_a.log
loglevel debug
