name: 'Upload Test Failures'
description: 'Upload test failure artifacts'
inputs:
  job-name:
    description: 'Unique name for the artifact'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload test failures
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: test-failures-${{ inputs.job-name }}
        path: test-failures/
