#!/bin/sh
#
# Simple server init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

### BEGIN INIT INFO
# Provides:     valkey_6379
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Valkey data structure server
# Description:          Valkey data structure server. See https://valkey.io
### END INIT INFO

VALKEYPORT=6379
EXEC=/usr/local/bin/valkey-server
CLIEXEC=/usr/local/bin/valkey-cli

PIDFILE=/var/run/valkey_${VALKEYPORT}.pid
CONF="/etc/valkey/${VALKEYPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Valkey server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $VALKEYPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Valkey to shutdown ..."
                    sleep 1
                done
                echo "Valkey stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
