name: Daily

on:
  pull_request:
    branches:
      # any PR to a release branch.
      - "[0-9].[0-9]"
      - "unstable"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      skipjobs:
        description: "jobs to skip (delete the ones you wanna keep, do not leave empty)"
        default: "valgrind,sanitizer,tls,freebsd,macos,alpine,32bit,iothreads,ubuntu,rpm-distros,malloc,specific,fortify,reply-schema,arm"
      skiptests:
        description: "tests to skip (delete the ones you wanna keep, do not leave empty)"
        default: "valkey,modules,sentinel,cluster,unittest,large-memory"
      test_args:
        description: "extra test arguments"
        default: ""
      cluster_test_args:
        description: "extra cluster / sentinel test arguments"
        default: ""
      use_repo:
        description: "repo owner and name"
        default: "valkey-io/valkey"
      use_git_ref:
        description: "git branch or sha to use"
        default: "unstable"

concurrency:
  group: daily-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-ubuntu-arm:
    runs-on: ubuntu-24.04-arm
    if: |
      (github.event_name == 'workflow_dispatch' ||
        (github.event_name == 'schedule' && github.repository == 'valkey-io/valkey') ||
        (github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'run-extra-tests') || github.event.pull_request.base.ref != 'unstable'))) &&
      (!contains(github.event.inputs.skipjobs, 'ubuntu') || !contains(github.event.inputs.skipjobs, 'arm'))
    timeout-minutes: 14400
    steps:
      - name: prep
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "GITHUB_REPOSITORY=${{github.event.inputs.use_repo}}" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF=${{github.event.inputs.use_git_ref}}" >> $GITHUB_ENV
          echo "skipjobs: ${{github.event.inputs.skipjobs}}"
          echo "skiptests: ${{github.event.inputs.skiptests}}"
          echo "test_args: ${{github.event.inputs.test_args}}"
          echo "cluster_test_args: ${{github.event.inputs.cluster_test_args}}"
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}
      - name: make
        run: make all-with-unit-tests SERVER_CFLAGS='-Werror'
      - name: testprep
        run: sudo apt-get install tcl8.6 tclx
      - name: test
        if: true && !contains(github.event.inputs.skiptests, 'valkey')
        run: ./runtest ${{ github.event_name != 'pull_request' && '--accurate' || '' }} --verbose --dump-logs ${{github.event.inputs.test_args}}
      - name: module api test
        if: true && !contains(github.event.inputs.skiptests, 'modules')
        run: CFLAGS='-Werror' ./runtest-moduleapi --verbose --dump-logs ${{github.event.inputs.test_args}}
      - name: sentinel tests
        if: true && !contains(github.event.inputs.skiptests, 'sentinel')
        run: ./runtest-sentinel ${{github.event.inputs.cluster_test_args}}
      - name: cluster tests
        if: true && !contains(github.event.inputs.skiptests, 'cluster')
        run: ./runtest-cluster ${{github.event.inputs.cluster_test_args}}
      - name: unittest
        if: true && !contains(github.event.inputs.skiptests, 'unittest')
        run: ./src/valkey-unit-tests --accurate


  notify-about-job-results:
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'schedule' && github.repository == 'valkey-io/valkey'
    needs:
      - test-ubuntu-arm
    steps:
      - name: Collect job status
        run: |
          FAILED_JOBS=()
          NEEDS_JSON='${{ toJSON(needs) }}'
          JOBS=($(echo "$NEEDS_JSON" | jq 'keys' | tr -d '[] ,'))
          for JOB in ${JOBS[@]}; do
            JOB_RESULT=$(echo "$NEEDS_JSON" | jq ".[$JOB][\"result\"]" | tr -d '"')
            if [ $JOB_RESULT = "failure" ]; then
              FAILED_JOBS+=($JOB)
            fi
          done

          if [[ ${#FAILED_JOBS[@]} -ne 0 ]]; then
            echo "FAILED_JOBS=${FAILED_JOBS[@]}" >> $GITHUB_ENV
            echo "STATUS=failure" >> $GITHUB_ENV
          else
            echo "STATUS=success" >> $GITHUB_ENV
          fi
      - name: Notify about results
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ env.STATUS }}
          notify_when: "failure"
          notification_title: "Daily test run <${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}|Failure>"
          message_format: ":fire: Tests failed: ${{ env.FAILED_JOBS }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK_URL }}
