name: Provenance Guard

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Run Provenance Check
        uses: valkey-io/verify-provenance@fcf3a6b3f2bd0215f0bdce0e724d2483ce76a31e
        with:
          source_repo: "redis/redis"
          target_repo: "${{ github.repository }}"
          branding_pairs: "Redis:Valkey"
          prefix_pairs: "RM_:VM_"
          source_brand: "Redis"
          target_brand: "Valkey"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          db_branch: "provenance-guard-db"
